'use strict';
const $=id=>document.getElementById(id);
const defaultEvidence=[
{id:'halloween',title:'Halloween update wording',description:'The current update information points toward Halloween as the next major update window.',type:'confirmed',status:'confirmed',weight:20},
{id:'prog',title:'CC response: “prog accurate”',description:'A creator response to the shared prediction strongly supports the general forecast, without making every detail official.',type:'clue',status:'confirmed',weight:16},
{id:'levi',title:'Levi reaction: “Oh dang”',description:'A reaction to the prediction is useful as a signal, but is not a direct release confirmation.',type:'clue',status:'confirmed',weight:7},
{id:'backstage',title:'Backstage / John WIP',description:'Reported WIP footage suggests substantial remaster development. Treat individual assets as unconfirmed until released.',type:'leak',status:'unconfirmed',weight:10},
{id:'bowling',title:'Bowling alley',description:'Reported remaster footage includes a bowling-alley area.',type:'leak',status:'unconfirmed',weight:10},
{id:'animatronic',title:'Tree-stage / animatronic clues',description:'Reported WIP material contains tree-stage and animatronic-related content.',type:'leak',status:'unconfirmed',weight:10},
{id:'pharaoh',title:'Pharaoh Betty Beaks',description:'Reported WIP/leak material points to a Pharaoh skin.',type:'leak',status:'unconfirmed',weight:10},
{id:'kitchen',title:'Kitchen reveal',description:'Reported remaster footage includes a kitchen-related reveal.',type:'leak',status:'unconfirmed',weight:10}
];
const additions=['Expanded/remastered Keyhunt environment','Bowling alley area','Tree-stage / animatronic content','Expanded office/backstage-style areas','Kitchen reveal','New/customized character and skin content','John-related material should remain WIP until confirmed'];
const leaks=['Donny Halloween skin','Paulie red rat chef hat','Doughy/Dougly purple sweater star','Red bunny hollow-eye look','John WIP black Paulie polo','John peeking/stalking-style WIP','Pharaoh Betty Beaks','Backstage footage'];
const easter=['Rat / animatronic connections','Backstage references','Character costume details','Environmental details visible in WIP footage','Possible callbacks to earlier NSAP material'];
const questions=['Will it release in the Halloween update?','Which leaked assets survive?','How much does the objective/map flow change?','Does John get a direct gameplay role?','Are any cutscene-like ideas actually planned?'];
const timeline=[['2026-10-03','Weekly Update','Lobby Play UI, matchmaking improvements, heavy lobby optimization and other systems landed; Halloween was announced as next week.'],['2026-10-06','Prediction shared','The prediction was shared with an NSAP CC who has talked to LB and Levia. LB replied “prog accurate”; Levi replied “Oh dang.”'],['2026-10-07','Forecast tracker','This evidence dashboard was created to separate confirmed information from leaks, clues and theories.']];
function load(k,f){try{const v=localStorage.getItem(k);return v?JSON.parse(v):structuredClone(f)}catch(e){console.error(e);return structuredClone(f)}}
function save(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){console.error(e)}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
let evidence=load('khEvidence',defaultEvidence), history=load('khHistory',[]);
function score(){const positive=evidence.reduce((n,e)=>n+Number(e.weight||0),0);return Math.round(Math.max(5,Math.min(95,48+positive*.55)))}
function render(){const s=score(),n=100-s;$('score').textContent=s+'%';$('thisPct').textContent=s+'%';$('nextPct').textContent=n+'%';$('scenarioThis').textContent=s+'%';$('scenarioNext').textContent=n+'%';$('bar').style.width=s+'%';$('call').textContent=s>=60?'THIS UPDATE':'NEXT UPDATE';$('reason').textContent=s>=60?'The current evidence stack leans toward the current update window.':'The evidence is not strong enough for the current window; next update leads.';$('count').textContent=evidence.length;$('confirmed').textContent=evidence.filter(e=>e.status==='confirmed').length;$('leaks').textContent=evidence.filter(e=>e.type==='leak').length;$('trend').textContent=s>=60?'↑':'→';$('trendText').textContent=s>=60?'current window favored':'next window favored';$('signals').innerHTML=[...evidence].sort((a,b)=>b.weight-a.weight).slice(0,5).map(e=>`<div class="signal"><b>${esc(e.title)}</b><small>${esc(e.type)} • +${e.weight} weight</small></div>`).join('');const q=$('search').value.toLowerCase(),t=$('type').value,st=$('status').value;const list=evidence.filter(e=>(t==='all'||e.type===t)&&(st==='all'||e.status===st)&&(`${e.title} ${e.description}`.toLowerCase().includes(q)));$('cards').innerHTML=list.length?list.map(e=>`<article class="evidence"><span class="badge ${esc(e.type)}">${esc(e.type.toUpperCase())}</span><h3>${esc(e.title)}</h3><p>${esc(e.description)}</p><div class="foot"><span>${esc(e.status)}</span><b>+${e.weight}</b></div></article>`).join(''):'<article class="panel"><p>No evidence matches this filter.</p></article>';renderHistory()}
function list(id,a){$(id).innerHTML=a.map(x=>`<li>${esc(x)}</li>`).join('')}
list('additions',additions);list('leakList',leaks);list('easter',easter);list('questions',questions);$('timelineList').innerHTML=timeline.map(e=>`<article class="event"><time>${e[0]}</time><h3>${esc(e[1])}</h3><p>${esc(e[2])}</p></article>`).join('');
function snap(){const s=score();history.push({date:new Date().toLocaleString(),score:s,call:s>=60?'THIS UPDATE':'NEXT UPDATE'});save('khHistory',history)}
function renderHistory(){$('history').innerHTML=history.length?history.slice().reverse().map(h=>`<div><span>${esc(h.date)}</span><b>${esc(h.call)} • ${h.score}%</b></div>`).join(''):'<div><span>No snapshots yet.</span><span>Add evidence to create one.</span></div>'}
$('add').onclick=()=>{ $('dialog').showModal() };$('close').onclick=()=>$('dialog').close();$('form').onsubmit=e=>{e.preventDefault();const item={id:crypto.randomUUID(),title:$('evTitle').value.trim(),description:$('evDesc').value.trim(),type:$('evType').value,status:$('evStatus').value,weight:Number($('evWeight').value)};if(!item.title||!item.description||!Number.isFinite(item.weight))return;evidence.push(item);save('khEvidence',evidence);e.target.reset();$('evWeight').value=7;$('dialog').close();snap();render()};['search','type','status'].forEach(id=>$(id).addEventListener('input',render));$('clear').onclick=()=>{history=[];save('khHistory',history);renderHistory()};$('theme').onclick=()=>{document.documentElement.classList.toggle('light');$('theme').textContent=document.documentElement.classList.contains('light')?'☀':'☾'};$('share').onclick=async()=>{const text=`KH Remaster Forecast: ${score()}% THIS UPDATE • ${100-score()}% NEXT UPDATE`;try{if(navigator.share)await navigator.share({title:'KH Remaster Forecast',text});else await navigator.clipboard.writeText(text)}catch(e){console.error(e)}};render();
