'use strict';
const DEFAULT={config:{thisName:'This update',thisDesc:'Current Halloween/update window',nextName:'Next update',nextDesc:'If current window passes',base:48},evidence:[
{id:'official-halloween',title:'Official Halloween update wording',description:'The update page has indicated Halloween as the next major update window, making this a natural remaster candidate.',type:'confirmed',status:'confirmed',weight:20},
{id:'prog-accurate',title:'CC response: “prog accurate”',description:'A community creator response described the shared prediction as program-accurate. Useful signal, not a release announcement.',type:'clue',status:'confirmed',weight:16},
{id:'levi-reaction',title:'Levi reaction: “Oh dang”',description:'Levi reacted to the prediction shared through an NSAP CC. Treat as a signal rather than direct confirmation.',type:'clue',status:'confirmed',weight:7},
{id:'backstage',title:'Backstage / John WIP footage',description:'Reported footage includes a backstage area and John-related WIP material. WIP does not guarantee final inclusion.',type:'leak',status:'unconfirmed',weight:10},
{id:'bowling',title:'Bowling alley / expanded locations',description:'Reported remaster footage and WIP clues include a bowling alley and expanded environments.',type:'leak',status:'unconfirmed',weight:10},
{id:'animatronics',title:'Tree-stage / animatronic clues',description:'Reported WIP material includes a tree stage and animatronic-related content.',type:'leak',status:'unconfirmed',weight:10},
{id:'pharaoh',title:'Pharaoh Betty Beaks',description:'Reported WIP material points to a Pharaoh skin for Betty Beaks.',type:'leak',status:'unconfirmed',weight:10},
{id:'kitchen',title:'Kitchen reveal',description:'Reported remaster footage includes a kitchen-related reveal, suggesting substantial environment work.',type:'leak',status:'unconfirmed',weight:10}],
additions:['Expanded / remastered Keyhunt environment','Bowling alley area','Tree-stage / animatronic content','Expanded office / backstage-style areas','Kitchen reveal','New or customized character / skin content','John-related material — still WIP, not guaranteed'],
leaks:['Donny Halloween skin','Paulie red rat chef hat','Doughy/Dougly purple sweater star','Red bunny with hollow-looking eyes','John WIP black Paulie polo','John peeking / stalking-style WIP','Pharaoh Betty Beaks','Backstage footage'],
easter:['Rat / animatronic connections','Backstage references','Character costume details','Environmental details visible in WIP footage','Possible visual callbacks to earlier NSAP material'],
questions:['Will the remaster release in the Halloween update?','Which leaked/WIP assets survive into the final build?','How much does the map/objective flow change?','Will John have a direct gameplay role?','Are any cutscene-like ideas actually planned?'],
timeline:[['2026-10-03','Weekly Update','Lobby Play UI, matchmaking improvements, optimization and other systems land; Halloween is announced as next week.'],['2026-10-06','Prediction shared','The prediction summary is shared with an NSAP CC who has talked to LB and Levia. LB replies “prog accurate”; Levi replies “Oh dang.”'],['2026-10-07','Forecast tracker','The red forecast dashboard is created to separate evidence from theories and score the release window.']]};
let data=load('khData',DEFAULT), history=load('khHistory',[]);
const $=id=>document.getElementById(id);function clone(v){return JSON.parse(JSON.stringify(v))}function load(k,f){try{const r=localStorage.getItem(k);return r?JSON.parse(r):clone(f)}catch(e){console.error('Load failed',e);return clone(f)}}function save(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){console.error('Save failed',e)}}function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function score(){const positive=data.evidence.reduce((n,e)=>n+Number(e.weight||0),0);const unconfirmedPenalty=data.evidence.filter(e=>e.status==='unconfirmed'&&e.type==='theory').reduce((n,e)=>n+Number(e.weight||0)*.25,0);return Math.round(Math.max(5,Math.min(95,Number(data.config.base)+positive*.55-unconfirmedPenalty)))}
function render(){const s=score(),n=100-s;$('score').textContent=s+'%';$('thisPct').textContent=s+'%';$('nextPct').textContent=n+'%';$('scenarioThis').textContent=s+'%';$('scenarioNext').textContent=n+'%';$('bar').style.width=s+'%';$('ring').style.background=`radial-gradient(circle,#14090a 58%,transparent 59%),conic-gradient(var(--red) ${s}%,#341417 0)`;$('call').textContent=s>=60?data.config.thisName.toUpperCase():data.config.nextName.toUpperCase();$('reason').textContent=s>=60?'The evidence stack currently favors the current update window.':'The current evidence is not strong enough; the next update leads.';$('count').textContent=data.evidence.length;$('confirmed').textContent=data.evidence.filter(e=>e.status==='confirmed').length;$('leaks').textContent=data.evidence.filter(e=>e.type==='leak').length;$('weight').textContent=data.evidence.reduce((n,e)=>n+Number(e.weight||0),0);$('trend').textContent=s>=60?'↑':'→';$('trendText').textContent=s>=60?'current window favored':'next window favored';$('thisName').textContent=data.config.thisName;$('thisDesc').textContent=data.config.thisDesc;$('nextName').textContent=data.config.nextName;$('nextDesc').textContent=data.config.nextDesc;$('later').textContent=s<40?'MED':'LOW';$('updated').textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});
const top=[...data.evidence].sort((a,b)=>b.weight-a.weight).slice(0,5);$('signals').innerHTML=top.map(e=>`<div class="signal"><b>${esc(e.title)}</b><small>${esc(e.type)} • +${e.weight} weight • ${esc(e.status)}</small></div>`).join('');
const q=$('search').value.toLowerCase(),t=$('type').value,st=$('status').value;const list=data.evidence.filter(e=>(t==='all'||e.type===t)&&(st==='all'||e.status===st)&&`${e.title} ${e.description}`.toLowerCase().includes(q));$('cards').innerHTML=list.length?list.map(e=>`<article class="evidence-card"><span class="badge ${esc(e.type)}">${esc(e.type.toUpperCase())}</span><h3>${esc(e.title)}</h3><p>${esc(e.description)}</p><div class="card-foot"><span>${esc(e.status)}</span><b>+${e.weight}</b></div></article>`).join(''):'<article class="panel"><p>No matching evidence.</p></article>';
$('additions').innerHTML=data.additions.map(x=>`<li>${esc(x)}</li>`).join('');$('leakList').innerHTML=data.leaks.map(x=>`<li>${esc(x)}</li>`).join('');$('easter').innerHTML=data.easter.map(x=>`<li>${esc(x)}</li>`).join('');$('questions').innerHTML=data.questions.map(x=>`<li>${esc(x)}</li>`).join('');$('timelineList').innerHTML=data.timeline.map(x=>`<article class="timeline-item"><time>${esc(x[0])}</time><h3>${esc(x[1])}</h3><p>${esc(x[2])}</p></article>`).join('');$('history').innerHTML=history.length?history.slice().reverse().map(h=>`<div class="history-row"><span>${esc(h.date)}</span><b>${esc(h.call)} • ${h.score}%</b></div>`).join(''):'<article class="panel"><p>No snapshots yet.</p></article>';
}
function snapshot(){const s=score();history.push({date:new Date().toLocaleString(),score:s,call:s>=60?data.config.thisName.toUpperCase():data.config.nextName.toUpperCase()});save('khHistory',history);render()}
$('add').onclick=()=>$('dialog').showModal();$('close').onclick=()=>$('dialog').close();$('form').onsubmit=e=>{e.preventDefault();data.evidence.push({id:crypto.randomUUID(),title:$('evTitle').value.trim(),description:$('evDesc').value.trim(),type:$('evType').value,status:$('evStatus').value,weight:Number($('evWeight').value)});save('khData',data);e.target.reset();$('dialog').close();snapshot()};['search','type','status'].forEach(id=>$(id).addEventListener('input',render));
$('addTimeline').onclick=()=>$('timelineDialog').showModal();$('timelineClose').onclick=()=>$('timelineDialog').close();$('timelineForm').onsubmit=e=>{e.preventDefault();data.timeline.push([$('tlDate').value,$('tlTitle').value.trim(),$('tlDesc').value.trim()]);data.timeline.sort((a,b)=>a[0].localeCompare(b[0]));save('khData',data);e.target.reset();$('timelineDialog').close();render()};
$('cfgThis').value=data.config.thisName;$('cfgThisDesc').value=data.config.thisDesc;$('cfgNext').value=data.config.nextName;$('cfgNextDesc').value=data.config.nextDesc;$('cfgBase').value=data.config.base;$('saveConfig').onclick=()=>{data.config={thisName:$('cfgThis').value.trim()||'This update',thisDesc:$('cfgThisDesc').value.trim()||'Current update window',nextName:$('cfgNext').value.trim()||'Next update',nextDesc:$('cfgNextDesc').value.trim()||'If current window passes',base:Math.max(0,Math.min(100,Number($('cfgBase').value)||48))};save('khData',data);snapshot()};
$('snapshot').onclick=snapshot;$('clear').onclick=()=>{history=[];save('khHistory',history);render()};$('reset').onclick=()=>{if(confirm('Reset all saved dashboard changes?')){data=clone(DEFAULT);history=[];save('khData',data);save('khHistory',history);location.reload()}};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({data,history},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='kh-remaster-forecast-data.json';a.click();URL.revokeObjectURL(url)};$('import').onclick=()=>$('importFile').click();$('importFile').onchange=()=>{const file=$('importFile').files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const x=JSON.parse(reader.result);if(!x.data||!Array.isArray(x.data.evidence)||!x.data.config)throw new Error('Invalid export');data=x.data;history=Array.isArray(x.history)?x.history:[];save('khData',data);save('khHistory',history);location.reload()}catch(e){alert('Import failed: '+e.message)}};reader.readAsText(file)};
$('theme').onclick=()=>{document.body.classList.toggle('light');$('theme').textContent=document.body.classList.contains('light')?'☀':'☾'};$('share').onclick=async()=>{const text=`KH Remaster Forecast: ${score()}% ${score()>=60?data.config.thisName:data.config.nextName}`;try{if(navigator.share)await navigator.share({title:'KH Remaster Forecast',text});else await navigator.clipboard.writeText(text)}catch(e){console.error('Share failed',e)}};$('year').textContent='© '+new Date().getFullYear();render();
